authTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: auth
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: user
        AttributeType: S
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: userToId
        KeySchema:
          - AttributeName: user
            KeyType: HASH
        Projection:
          NonKeyAttributes:
          - userId
          ProjectionType: INCLUDE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1