createUser:
    handler: create.main
    events:
    - http:
        path: api/user
        method: post
        cors: true
        authorizer: aws_iam
authenticate:
    handler: authenticate.main
    events:
        - http:
            path: api/auth
            method: post
            cors: true
            authorizer: aws_iam
createHive:
    handler: hive.create
    events:
      - http:
          path: api/hive
          method: post
          cors: true
          authorizer: aws_iam
getUsersHives:
    handler: hive.getUsersHives
    events:
      - http:
          path: api/hive/{userId}
          method: get
          cors: true
          authorizer: aws_iam
getSpecifiedHive:
    handler: hive.getSpecifiedHive
    events:
      - http:
          path: api/hive/{userId}/{hiveId}
          method: get
          cors: true
          authorizer: aws_iam
updateHive:
    handler: hive.updateHive
    events:
      - http:
          path: api/hive
          method: patch
          cors: true
          authorize: aws_iam
deleteHive:
    handler: hive.deleteHive
    events:
      - http:
          path: api/hive
          method: delete
          cors: true
          authorize: aws_iam

